### ISSUE TITLE
After changing my theme to VSCodeDarkPlus the welcome page becomes completely dark

### ISSUE THREAD

**Issue by ACCSCI** [PsychedelicShayna/QtCreatorTheme-VSCodeDarkPlus#2] opened 2024-12-18 08:36 UTC
Hello,

I hope this message finds you well.

I am experiencing an issue with your theme in Qt Creator, which seems to be similar to the one described here: [issue link](https://github.com/catppuccin/qtcreator/issues/2). After applying the theme, the welcome screen in Qt Creator becomes completely black, making it difficult to use.

Here are my system and software details:

System Version: Windows 11 22631
Qt Version: 14.0.2
I really appreciate the work you've put into creating this theme, but this issue is quite disruptive. Any assistance you could provide would be greatly appreciated.

Thank you for your time and consideration.
![image](https://github.com/user-attachments/assets/4684ef78-7b48-4624-8cbb-4b6ab0fdd491)

**Comment by PsychedelicShayna** [comment] 2024-12-19 04:24
On the contrary, thanks for bringing this to my attention. It seems Qt changed certain things about their theme engine after a certain update. I've since stopped using Qt/C++ as my go-to, so this would have flown right past me had you not have mentioned it. I'm going to try to replicate it right now, I have the same Qt version, but I'm not on Windows anymore. Though from the issue you linked, I don't think that'll make a difference, seems like a change in the theme structure.

I'm on it.

**Comment by PsychedelicShayna** [comment] 2024-12-19 05:58
@ACCSCI Figmatokens. That's the cause. __Why do they have to complicate things..__

So they added *another* file that makes up a theme. I naturally first tried to load _just_ the editor theme without the entire UI theme, and holy yellow nightmare.

So simply not applying the UI theme and just applying the editor theme (which is is basically the most important part) isn't an option.

Using dark.figmatokens in the default themes directory as a reference, I hacked off pieces and replaced background colors until the editor theme looks accurate again.. well somewhat accurate.

There's still those annoying bright white indentation guides. I'll have to find the value for that one.

Who knows this could actually be a good thing, I did zero research into the new system because I'm frankly short on time, but from the look of it, maybe it could solve the Blue/Purple editor theme split, and more precisely define colors for specific tokens? I'm not sure.

Either way here's a modified .creatortheme and a .figmatokens file for the moment, which should serve as temporary duct tape. There's probably going to be issues and inaccuracies, but, I mean.. duct tape!

To anyone else following this issue, any info or PR's are welcome. I'll have a deeper look into the new figmatokens system in my own personal time.

I might post an update in the following hours because those white indentation guides are _really, really_ annoying. For now I suggest turning it off entirely. Probably missing a value, or perhaps opacity since that seems to be a thing now.

[duct-tape.zip](https://github.com/user-attachments/files/18193231/duct-tape.zip)

Place them both next to each other, where the .creatortheme file goes.

Untested on Windows. Let me know if it works for you, and if it does, could you post any inconsistencies and color problems you encounter here? There's definitely gonna be some. Feel free to spam the issue with them as you find them, I don't mind. Thanks!

**Comment by ACCSCI** [comment] 2024-12-19 06:38
Just wanted to let you know that I used your new patch and it worked like a charm on Windows! The problem is totally gone. Thanks so much for your hard work, you're awesome! 😊

**Comment by PsychedelicShayna** [comment] 2024-12-19 15:22
Really? It just.. worked? Just like that? _Huh.._
I thought I was gonna have to edit a bunch more stuff.

Like, are you seeing the same annoying bright white indentation guides I am? Is this just a me thing?

![ksnip_tmp_OoMHqL](https://github.com/user-attachments/assets/2a57f02c-c594-43a5-bd68-06b0259da572)


Have you used this theme before or is this the first time? If it's the first, I'm guessing you wouldn't notice the inconsistencies if there are any, but if it's not, then do keep an eye out. Even if a color is off by just like.. #414141 -> #414241, that's gotta get fixed at some point, since the whole reason I made this theme is because all the others were halfassed, and I want to keep this as true to the original as possible.

Glad it worked out for you though! If you spot anything lmk. I'll go ahead and include that uhm.. duct tape, in the README and post a new release. Still this is such a janky fix.. but hey at least it works now!

**Comment by PsychedelicShayna** [comment] 2024-12-19 15:29
Actually creating a new issue would probably make more sense.. since the original title no longer applies, but I don't want to edit it, and would rather leave an archive.. I'll close this one and open a new one referencing this one, and the folks over at Catppuccin in case they can weigh in on this, or perhaps the duct tape could serve them as well, idk. Let's see.

**Closed as completed by PsychedelicShayna** 2024-12-19 15:29 UTC
Labels: bug
